name: meteorologia
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^1.19.2"
  firebase_auth: "^1.1.0"
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  page_indicator: ^0.4.1
  flutter_hooks: ^0.18.5+1
  cupertino_icons: ^1.0.2
  google_sign_in: 5.4.0
  cloud_firestore: ^3.3.0
  firebase_storage: ^10.3.2
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  google_maps_flutter: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/